apiVersion: v1
kind: ConfigMap
metadata:
  name: inferno-autoscaler-variantautoscaling-config
  namespace: inferno-autoscaler-system
  labels:
    app.kubernetes.io/name: inferno-autoscaler
    app.kubernetes.io/managed-by: kustomize
data:
  # Prometheus configuration
  PROMETHEUS_BASE_URL: "http://kube-prometheus-stack-prometheus.inferno-autoscaler-monitoring.svc.cluster.local:9090"
  
  # Optimization configuration
  GLOBAL_OPT_INTERVAL: "60s"
  GLOBAL_OPT_TRIGGER: "false" 