apiVersion: v1
kind: Service
metadata:
  name: inferno-webhook
  namespace: inferno-system
  labels:
    app: inferno-webhook
spec:
  type: ClusterIP
  selector:
    app: inferno-webhook
  ports:
  - name: webhook
    port: 443
    targetPort: 9443
    protocol: TCP
