# This rule is not used by the project inferno-autoscaler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the llmd.llm-d.ai.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: inferno-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: variantautoscaling-editor-role
rules:
- apiGroups:
  - llmd.llm-d.ai
  resources:
  - variantautoscalings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llmd.llm-d.ai
  resources:
  - VariantAutoscalingss/status
  verbs:
  - get
