apiVersion: llmd.ai/v1alpha1
# Optimizing a variant, create only when the model is deployed and serving traffic
# this is for the collector the collect existing (previous) running metrics of the variant.
kind: Optimizer
metadata:
  # Unique name of the variant
  name: varaint-granite-13b-tp-4-a100
  namespace: default
  labels:
    inference.optimization/modelName: granite-13b
# This is essentially static input to the optimizer
spec:
  # OpenAI API compatible name of the model
  modelID: granite-13b
  # Add SLOs in configmap, add reference to this per model data
  # to avoid duplication and Move to ISOs when available
  sloClassRef:
    # Configmap name to load in the same namespace as optimizer object
    # we start with static (non-changing) ConfigMaps (for ease of implementation only)
    name: premium-slo
    # Key (modelID) present inside configmap
    key: granite-13b
  # Static profiled benchmarked data for a variant running on different accelerators
  modelProfile:
    accelerators:
      - acc: "A100"
        accCount: 1
        alpha: "20.58"
        beta: "0.41"
        maxBatchSize: 32
        atTokens: 512
      - acc: "G2"
        accCount: 1
        alpha: "17.15"
        beta: "0.34"
        maxBatchSize: 38
        atTokens: 512