apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: vllm
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    environment: test
    helm-release-name: vllm
    model: opt125m
    release: test
  name: vllm-opt125m-deployment-vllm
  namespace: default
spec:
  progressDeadlineSeconds: 1200
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      environment: test
      helm-release-name: vllm
      model: opt125m
      release: test
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        environment: test
        helm-release-name: vllm
        model: opt125m
        release: test
    spec:
      containers:
      - command:
        - vllm
        - serve
        - facebook/opt-125m
        - --host
        - 0.0.0.0
        - --port
        - "8000"
        env:
        - name: HF_HOME
          value: /tmp
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: vllm/vllm-openai:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: vllm
        ports:
        - containerPort: 8000
          name: container-port
          protocol: TCP
        - containerPort: 55555
          name: zmq-port
          protocol: TCP
        - containerPort: 9999
          name: ucx-port
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            cpu: "6"
            memory: 16Gi
            nvidia.com/gpu: "1"
        securityContext:
          runAsNonRoot: false
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostname: vllm-opt125m-vllm-stack
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      subdomain: vllm-opt125m-engine-service
      terminationGracePeriodSeconds: 30